terminate called after throwing an instance of 'std::runtime_error'
  what():  Error enqueuing kernel: -54
